// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: shared/proto/events.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Video transport protocol negotiated at handshake time
nonisolated enum TDVideoTransport: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// Wi-Fi mode: standard UDP datagrams
  case udp // = 0

  /// USB mode: reliable TCP stream tunnelled over adb forward
  case tcp // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .udp
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .udp
    case 1: self = .tcp
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .udp: return 0
    case .tcp: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [TDVideoTransport] = [
    .udp,
    .tcp,
  ]

}

/// Base message wrapper for all data sent over the control TCP connection
nonisolated struct TDControlPacket: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var payload: TDControlPacket.OneOf_Payload? = nil

  var handshakeRequest: TDHandshakeRequest {
    get {
      if case .handshakeRequest(let v)? = payload {return v}
      return TDHandshakeRequest()
    }
    set {payload = .handshakeRequest(newValue)}
  }

  var handshakeResponse: TDHandshakeResponse {
    get {
      if case .handshakeResponse(let v)? = payload {return v}
      return TDHandshakeResponse()
    }
    set {payload = .handshakeResponse(newValue)}
  }

  var keepAlive: TDKeepAlive {
    get {
      if case .keepAlive(let v)? = payload {return v}
      return TDKeepAlive()
    }
    set {payload = .keepAlive(newValue)}
  }

  var inputEvent: TDInputEvent {
    get {
      if case .inputEvent(let v)? = payload {return v}
      return TDInputEvent()
    }
    set {payload = .inputEvent(newValue)}
  }

  var telemetry: TDTelemetryFeedback {
    get {
      if case .telemetry(let v)? = payload {return v}
      return TDTelemetryFeedback()
    }
    set {payload = .telemetry(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Payload: Equatable, Sendable {
    case handshakeRequest(TDHandshakeRequest)
    case handshakeResponse(TDHandshakeResponse)
    case keepAlive(TDKeepAlive)
    case inputEvent(TDInputEvent)
    case telemetry(TDTelemetryFeedback)

  }

  init() {}
}

/// Handshake Request from Client (Android) to Server (macOS)
nonisolated struct TDHandshakeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// e.g. "Samsung Tab S6 Lite"
  var clientDeviceName: String = String()

  /// e.g. 1920
  var preferredWidth: UInt32 = 0

  /// e.g. 1200
  var preferredHeight: UInt32 = 0

  /// e.g. 60
  var targetFps: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Handshake Response from Server (macOS) to Client (Android)
nonisolated struct TDHandshakeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var accepted: Bool = false

  /// e.g. "MacBook Air"
  var serverName: String = String()

  /// Actual virtual display resolution width
  var allocatedWidth: UInt32 = 0

  /// Actual virtual display resolution height
  var allocatedHeight: UInt32 = 0

  var negotiatedFps: UInt32 = 0

  /// UDP/TCP Port for video transmission
  var videoStreamPort: UInt32 = 0

  /// Transport protocol for video stream
  var videoTransport: TDVideoTransport = .udp

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Keep-Alive Packet for Heartbeat monitoring
nonisolated struct TDKeepAlive: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Monotonic server/client system timestamp
  var timestamp: UInt64 = 0

  var sequence: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// User Input Event forwarded from Android Client to macOS Server
nonisolated struct TDInputEvent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var action: TDInputEvent.ActionType = .actionDown

  /// Horizontal position [0.0 - 1.0]
  var xPercent: Float = 0

  /// Vertical position [0.0 - 1.0]
  var yPercent: Float = 0

  /// Scroll offsets (only for ACTION_SCROLL)
  var scrollDeltaX: Int32 = 0

  var scrollDeltaY: Int32 = 0

  /// For multi-touch gestures
  var pointerCount: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum ActionType: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case actionDown // = 0
    case actionUp // = 1
    case actionMove // = 2
    case actionScroll // = 3
    case UNRECOGNIZED(Int)

    init() {
      self = .actionDown
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .actionDown
      case 1: self = .actionUp
      case 2: self = .actionMove
      case 3: self = .actionScroll
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .actionDown: return 0
      case .actionUp: return 1
      case .actionMove: return 2
      case .actionScroll: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [TDInputEvent.ActionType] = [
      .actionDown,
      .actionUp,
      .actionMove,
      .actionScroll,
    ]

  }

  init() {}
}

/// Telemetry feedback from Android Client to macOS Server for Adaptive Bitrate
nonisolated struct TDTelemetryFeedback: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Percentage of packets dropped [0.0 - 100.0]
  var packetLossRate: Float = 0

  /// Latency jitter in milliseconds
  var averageJitterMs: Float = 0

  /// Total elapsed frame latency measured by client
  var endToEndLatencyMs: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "tabdisplay"

nonisolated extension TDVideoTransport: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UDP\0\u{1}TCP\0")
}

nonisolated extension TDControlPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ControlPacket"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}handshake_request\0\u{3}handshake_response\0\u{3}keep_alive\0\u{3}input_event\0\u{1}telemetry\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: TDHandshakeRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .handshakeRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .handshakeRequest(v)
        }
      }()
      case 2: try {
        var v: TDHandshakeResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .handshakeResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .handshakeResponse(v)
        }
      }()
      case 3: try {
        var v: TDKeepAlive?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .keepAlive(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .keepAlive(v)
        }
      }()
      case 4: try {
        var v: TDInputEvent?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .inputEvent(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .inputEvent(v)
        }
      }()
      case 5: try {
        var v: TDTelemetryFeedback?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .telemetry(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .telemetry(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .handshakeRequest?: try {
      guard case .handshakeRequest(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .handshakeResponse?: try {
      guard case .handshakeResponse(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .keepAlive?: try {
      guard case .keepAlive(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .inputEvent?: try {
      guard case .inputEvent(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .telemetry?: try {
      guard case .telemetry(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TDControlPacket, rhs: TDControlPacket) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension TDHandshakeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HandshakeRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}client_device_name\0\u{3}preferred_width\0\u{3}preferred_height\0\u{3}target_fps\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.clientDeviceName) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.preferredWidth) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.preferredHeight) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.targetFps) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clientDeviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.clientDeviceName, fieldNumber: 1)
    }
    if self.preferredWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.preferredWidth, fieldNumber: 2)
    }
    if self.preferredHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.preferredHeight, fieldNumber: 3)
    }
    if self.targetFps != 0 {
      try visitor.visitSingularUInt32Field(value: self.targetFps, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TDHandshakeRequest, rhs: TDHandshakeRequest) -> Bool {
    if lhs.clientDeviceName != rhs.clientDeviceName {return false}
    if lhs.preferredWidth != rhs.preferredWidth {return false}
    if lhs.preferredHeight != rhs.preferredHeight {return false}
    if lhs.targetFps != rhs.targetFps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension TDHandshakeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HandshakeResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}accepted\0\u{3}server_name\0\u{3}allocated_width\0\u{3}allocated_height\0\u{3}negotiated_fps\0\u{3}video_stream_port\0\u{3}video_transport\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.accepted) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.serverName) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.allocatedWidth) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.allocatedHeight) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.negotiatedFps) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.videoStreamPort) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self.videoTransport) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accepted != false {
      try visitor.visitSingularBoolField(value: self.accepted, fieldNumber: 1)
    }
    if !self.serverName.isEmpty {
      try visitor.visitSingularStringField(value: self.serverName, fieldNumber: 2)
    }
    if self.allocatedWidth != 0 {
      try visitor.visitSingularUInt32Field(value: self.allocatedWidth, fieldNumber: 3)
    }
    if self.allocatedHeight != 0 {
      try visitor.visitSingularUInt32Field(value: self.allocatedHeight, fieldNumber: 4)
    }
    if self.negotiatedFps != 0 {
      try visitor.visitSingularUInt32Field(value: self.negotiatedFps, fieldNumber: 5)
    }
    if self.videoStreamPort != 0 {
      try visitor.visitSingularUInt32Field(value: self.videoStreamPort, fieldNumber: 6)
    }
    if self.videoTransport != .udp {
      try visitor.visitSingularEnumField(value: self.videoTransport, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TDHandshakeResponse, rhs: TDHandshakeResponse) -> Bool {
    if lhs.accepted != rhs.accepted {return false}
    if lhs.serverName != rhs.serverName {return false}
    if lhs.allocatedWidth != rhs.allocatedWidth {return false}
    if lhs.allocatedHeight != rhs.allocatedHeight {return false}
    if lhs.negotiatedFps != rhs.negotiatedFps {return false}
    if lhs.videoStreamPort != rhs.videoStreamPort {return false}
    if lhs.videoTransport != rhs.videoTransport {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension TDKeepAlive: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KeepAlive"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}timestamp\0\u{1}sequence\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.sequence) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 1)
    }
    if self.sequence != 0 {
      try visitor.visitSingularUInt32Field(value: self.sequence, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TDKeepAlive, rhs: TDKeepAlive) -> Bool {
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.sequence != rhs.sequence {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension TDInputEvent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InputEvent"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}action\0\u{3}x_percent\0\u{3}y_percent\0\u{3}scroll_delta_x\0\u{3}scroll_delta_y\0\u{3}pointer_count\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.xPercent) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.yPercent) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.scrollDeltaX) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.scrollDeltaY) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.pointerCount) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.action != .actionDown {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 1)
    }
    if self.xPercent.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.xPercent, fieldNumber: 2)
    }
    if self.yPercent.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.yPercent, fieldNumber: 3)
    }
    if self.scrollDeltaX != 0 {
      try visitor.visitSingularInt32Field(value: self.scrollDeltaX, fieldNumber: 4)
    }
    if self.scrollDeltaY != 0 {
      try visitor.visitSingularInt32Field(value: self.scrollDeltaY, fieldNumber: 5)
    }
    if self.pointerCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.pointerCount, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TDInputEvent, rhs: TDInputEvent) -> Bool {
    if lhs.action != rhs.action {return false}
    if lhs.xPercent != rhs.xPercent {return false}
    if lhs.yPercent != rhs.yPercent {return false}
    if lhs.scrollDeltaX != rhs.scrollDeltaX {return false}
    if lhs.scrollDeltaY != rhs.scrollDeltaY {return false}
    if lhs.pointerCount != rhs.pointerCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension TDInputEvent.ActionType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ACTION_DOWN\0\u{1}ACTION_UP\0\u{1}ACTION_MOVE\0\u{1}ACTION_SCROLL\0")
}

nonisolated extension TDTelemetryFeedback: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TelemetryFeedback"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}packet_loss_rate\0\u{3}average_jitter_ms\0\u{3}end_to_end_latency_ms\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.packetLossRate) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.averageJitterMs) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.endToEndLatencyMs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.packetLossRate.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.packetLossRate, fieldNumber: 1)
    }
    if self.averageJitterMs.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.averageJitterMs, fieldNumber: 2)
    }
    if self.endToEndLatencyMs.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.endToEndLatencyMs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TDTelemetryFeedback, rhs: TDTelemetryFeedback) -> Bool {
    if lhs.packetLossRate != rhs.packetLossRate {return false}
    if lhs.averageJitterMs != rhs.averageJitterMs {return false}
    if lhs.endToEndLatencyMs != rhs.endToEndLatencyMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
