// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

@com.google.protobuf.Generated
public interface ControlPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tabdisplay.ControlPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
   * @return Whether the handshakeRequest field is set.
   */
  boolean hasHandshakeRequest();
  /**
   * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
   * @return The handshakeRequest.
   */
  com.tabdisplay.client.proto.HandshakeRequest getHandshakeRequest();
  /**
   * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
   */
  com.tabdisplay.client.proto.HandshakeRequestOrBuilder getHandshakeRequestOrBuilder();

  /**
   * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
   * @return Whether the handshakeResponse field is set.
   */
  boolean hasHandshakeResponse();
  /**
   * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
   * @return The handshakeResponse.
   */
  com.tabdisplay.client.proto.HandshakeResponse getHandshakeResponse();
  /**
   * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
   */
  com.tabdisplay.client.proto.HandshakeResponseOrBuilder getHandshakeResponseOrBuilder();

  /**
   * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
   * @return Whether the keepAlive field is set.
   */
  boolean hasKeepAlive();
  /**
   * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
   * @return The keepAlive.
   */
  com.tabdisplay.client.proto.KeepAlive getKeepAlive();
  /**
   * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
   */
  com.tabdisplay.client.proto.KeepAliveOrBuilder getKeepAliveOrBuilder();

  /**
   * <code>.tabdisplay.InputEvent input_event = 4;</code>
   * @return Whether the inputEvent field is set.
   */
  boolean hasInputEvent();
  /**
   * <code>.tabdisplay.InputEvent input_event = 4;</code>
   * @return The inputEvent.
   */
  com.tabdisplay.client.proto.InputEvent getInputEvent();
  /**
   * <code>.tabdisplay.InputEvent input_event = 4;</code>
   */
  com.tabdisplay.client.proto.InputEventOrBuilder getInputEventOrBuilder();

  /**
   * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
   * @return Whether the telemetry field is set.
   */
  boolean hasTelemetry();
  /**
   * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
   * @return The telemetry.
   */
  com.tabdisplay.client.proto.TelemetryFeedback getTelemetry();
  /**
   * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
   */
  com.tabdisplay.client.proto.TelemetryFeedbackOrBuilder getTelemetryOrBuilder();

  com.tabdisplay.client.proto.ControlPacket.PayloadCase getPayloadCase();
}
