// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

/**
 * <pre>
 * Base message wrapper for all data sent over the control TCP connection
 * </pre>
 *
 * Protobuf type {@code tabdisplay.ControlPacket}
 */
@com.google.protobuf.Generated
public final class ControlPacket extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tabdisplay.ControlPacket)
    ControlPacketOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ControlPacket");
  }
  // Use ControlPacket.newBuilder() to construct.
  private ControlPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ControlPacket() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_ControlPacket_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_ControlPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_ControlPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tabdisplay.client.proto.ControlPacket.class, com.tabdisplay.client.proto.ControlPacket.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HANDSHAKE_REQUEST(1),
    HANDSHAKE_RESPONSE(2),
    KEEP_ALIVE(3),
    INPUT_EVENT(4),
    TELEMETRY(5),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return HANDSHAKE_REQUEST;
        case 2: return HANDSHAKE_RESPONSE;
        case 3: return KEEP_ALIVE;
        case 4: return INPUT_EVENT;
        case 5: return TELEMETRY;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int HANDSHAKE_REQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
   * @return Whether the handshakeRequest field is set.
   */
  @java.lang.Override
  public boolean hasHandshakeRequest() {
    return payloadCase_ == 1;
  }
  /**
   * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
   * @return The handshakeRequest.
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.HandshakeRequest getHandshakeRequest() {
    if (payloadCase_ == 1) {
       return (com.tabdisplay.client.proto.HandshakeRequest) payload_;
    }
    return com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance();
  }
  /**
   * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.HandshakeRequestOrBuilder getHandshakeRequestOrBuilder() {
    if (payloadCase_ == 1) {
       return (com.tabdisplay.client.proto.HandshakeRequest) payload_;
    }
    return com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance();
  }

  public static final int HANDSHAKE_RESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
   * @return Whether the handshakeResponse field is set.
   */
  @java.lang.Override
  public boolean hasHandshakeResponse() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
   * @return The handshakeResponse.
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.HandshakeResponse getHandshakeResponse() {
    if (payloadCase_ == 2) {
       return (com.tabdisplay.client.proto.HandshakeResponse) payload_;
    }
    return com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance();
  }
  /**
   * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.HandshakeResponseOrBuilder getHandshakeResponseOrBuilder() {
    if (payloadCase_ == 2) {
       return (com.tabdisplay.client.proto.HandshakeResponse) payload_;
    }
    return com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance();
  }

  public static final int KEEP_ALIVE_FIELD_NUMBER = 3;
  /**
   * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
   * @return Whether the keepAlive field is set.
   */
  @java.lang.Override
  public boolean hasKeepAlive() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
   * @return The keepAlive.
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.KeepAlive getKeepAlive() {
    if (payloadCase_ == 3) {
       return (com.tabdisplay.client.proto.KeepAlive) payload_;
    }
    return com.tabdisplay.client.proto.KeepAlive.getDefaultInstance();
  }
  /**
   * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.KeepAliveOrBuilder getKeepAliveOrBuilder() {
    if (payloadCase_ == 3) {
       return (com.tabdisplay.client.proto.KeepAlive) payload_;
    }
    return com.tabdisplay.client.proto.KeepAlive.getDefaultInstance();
  }

  public static final int INPUT_EVENT_FIELD_NUMBER = 4;
  /**
   * <code>.tabdisplay.InputEvent input_event = 4;</code>
   * @return Whether the inputEvent field is set.
   */
  @java.lang.Override
  public boolean hasInputEvent() {
    return payloadCase_ == 4;
  }
  /**
   * <code>.tabdisplay.InputEvent input_event = 4;</code>
   * @return The inputEvent.
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.InputEvent getInputEvent() {
    if (payloadCase_ == 4) {
       return (com.tabdisplay.client.proto.InputEvent) payload_;
    }
    return com.tabdisplay.client.proto.InputEvent.getDefaultInstance();
  }
  /**
   * <code>.tabdisplay.InputEvent input_event = 4;</code>
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.InputEventOrBuilder getInputEventOrBuilder() {
    if (payloadCase_ == 4) {
       return (com.tabdisplay.client.proto.InputEvent) payload_;
    }
    return com.tabdisplay.client.proto.InputEvent.getDefaultInstance();
  }

  public static final int TELEMETRY_FIELD_NUMBER = 5;
  /**
   * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
   * @return Whether the telemetry field is set.
   */
  @java.lang.Override
  public boolean hasTelemetry() {
    return payloadCase_ == 5;
  }
  /**
   * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
   * @return The telemetry.
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.TelemetryFeedback getTelemetry() {
    if (payloadCase_ == 5) {
       return (com.tabdisplay.client.proto.TelemetryFeedback) payload_;
    }
    return com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance();
  }
  /**
   * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
   */
  @java.lang.Override
  public com.tabdisplay.client.proto.TelemetryFeedbackOrBuilder getTelemetryOrBuilder() {
    if (payloadCase_ == 5) {
       return (com.tabdisplay.client.proto.TelemetryFeedback) payload_;
    }
    return com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (com.tabdisplay.client.proto.HandshakeRequest) payload_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (com.tabdisplay.client.proto.HandshakeResponse) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (com.tabdisplay.client.proto.KeepAlive) payload_);
    }
    if (payloadCase_ == 4) {
      output.writeMessage(4, (com.tabdisplay.client.proto.InputEvent) payload_);
    }
    if (payloadCase_ == 5) {
      output.writeMessage(5, (com.tabdisplay.client.proto.TelemetryFeedback) payload_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.tabdisplay.client.proto.HandshakeRequest) payload_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.tabdisplay.client.proto.HandshakeResponse) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.tabdisplay.client.proto.KeepAlive) payload_);
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.tabdisplay.client.proto.InputEvent) payload_);
    }
    if (payloadCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.tabdisplay.client.proto.TelemetryFeedback) payload_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tabdisplay.client.proto.ControlPacket)) {
      return super.equals(obj);
    }
    com.tabdisplay.client.proto.ControlPacket other = (com.tabdisplay.client.proto.ControlPacket) obj;

    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1:
        if (!getHandshakeRequest()
            .equals(other.getHandshakeRequest())) return false;
        break;
      case 2:
        if (!getHandshakeResponse()
            .equals(other.getHandshakeResponse())) return false;
        break;
      case 3:
        if (!getKeepAlive()
            .equals(other.getKeepAlive())) return false;
        break;
      case 4:
        if (!getInputEvent()
            .equals(other.getInputEvent())) return false;
        break;
      case 5:
        if (!getTelemetry()
            .equals(other.getTelemetry())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + HANDSHAKE_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakeRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + HANDSHAKE_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getHandshakeResponse().hashCode();
        break;
      case 3:
        hash = (37 * hash) + KEEP_ALIVE_FIELD_NUMBER;
        hash = (53 * hash) + getKeepAlive().hashCode();
        break;
      case 4:
        hash = (37 * hash) + INPUT_EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getInputEvent().hashCode();
        break;
      case 5:
        hash = (37 * hash) + TELEMETRY_FIELD_NUMBER;
        hash = (53 * hash) + getTelemetry().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tabdisplay.client.proto.ControlPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tabdisplay.client.proto.ControlPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.ControlPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tabdisplay.client.proto.ControlPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Base message wrapper for all data sent over the control TCP connection
   * </pre>
   *
   * Protobuf type {@code tabdisplay.ControlPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tabdisplay.ControlPacket)
      com.tabdisplay.client.proto.ControlPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_ControlPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_ControlPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tabdisplay.client.proto.ControlPacket.class, com.tabdisplay.client.proto.ControlPacket.Builder.class);
    }

    // Construct using com.tabdisplay.client.proto.ControlPacket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (handshakeRequestBuilder_ != null) {
        handshakeRequestBuilder_.clear();
      }
      if (handshakeResponseBuilder_ != null) {
        handshakeResponseBuilder_.clear();
      }
      if (keepAliveBuilder_ != null) {
        keepAliveBuilder_.clear();
      }
      if (inputEventBuilder_ != null) {
        inputEventBuilder_.clear();
      }
      if (telemetryBuilder_ != null) {
        telemetryBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_ControlPacket_descriptor;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.ControlPacket getDefaultInstanceForType() {
      return com.tabdisplay.client.proto.ControlPacket.getDefaultInstance();
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.ControlPacket build() {
      com.tabdisplay.client.proto.ControlPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.ControlPacket buildPartial() {
      com.tabdisplay.client.proto.ControlPacket result = new com.tabdisplay.client.proto.ControlPacket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tabdisplay.client.proto.ControlPacket result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.tabdisplay.client.proto.ControlPacket result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1 &&
          handshakeRequestBuilder_ != null) {
        result.payload_ = handshakeRequestBuilder_.build();
      }
      if (payloadCase_ == 2 &&
          handshakeResponseBuilder_ != null) {
        result.payload_ = handshakeResponseBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          keepAliveBuilder_ != null) {
        result.payload_ = keepAliveBuilder_.build();
      }
      if (payloadCase_ == 4 &&
          inputEventBuilder_ != null) {
        result.payload_ = inputEventBuilder_.build();
      }
      if (payloadCase_ == 5 &&
          telemetryBuilder_ != null) {
        result.payload_ = telemetryBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tabdisplay.client.proto.ControlPacket) {
        return mergeFrom((com.tabdisplay.client.proto.ControlPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tabdisplay.client.proto.ControlPacket other) {
      if (other == com.tabdisplay.client.proto.ControlPacket.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case HANDSHAKE_REQUEST: {
          mergeHandshakeRequest(other.getHandshakeRequest());
          break;
        }
        case HANDSHAKE_RESPONSE: {
          mergeHandshakeResponse(other.getHandshakeResponse());
          break;
        }
        case KEEP_ALIVE: {
          mergeKeepAlive(other.getKeepAlive());
          break;
        }
        case INPUT_EVENT: {
          mergeInputEvent(other.getInputEvent());
          break;
        }
        case TELEMETRY: {
          mergeTelemetry(other.getTelemetry());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetHandshakeRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetHandshakeResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetKeepAliveFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetInputEventFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetTelemetryFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.HandshakeRequest, com.tabdisplay.client.proto.HandshakeRequest.Builder, com.tabdisplay.client.proto.HandshakeRequestOrBuilder> handshakeRequestBuilder_;
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     * @return Whether the handshakeRequest field is set.
     */
    @java.lang.Override
    public boolean hasHandshakeRequest() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     * @return The handshakeRequest.
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeRequest getHandshakeRequest() {
      if (handshakeRequestBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (com.tabdisplay.client.proto.HandshakeRequest) payload_;
        }
        return com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return handshakeRequestBuilder_.getMessage();
        }
        return com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     */
    public Builder setHandshakeRequest(com.tabdisplay.client.proto.HandshakeRequest value) {
      if (handshakeRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        handshakeRequestBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     */
    public Builder setHandshakeRequest(
        com.tabdisplay.client.proto.HandshakeRequest.Builder builderForValue) {
      if (handshakeRequestBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        handshakeRequestBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     */
    public Builder mergeHandshakeRequest(com.tabdisplay.client.proto.HandshakeRequest value) {
      if (handshakeRequestBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance()) {
          payload_ = com.tabdisplay.client.proto.HandshakeRequest.newBuilder((com.tabdisplay.client.proto.HandshakeRequest) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          handshakeRequestBuilder_.mergeFrom(value);
        } else {
          handshakeRequestBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     */
    public Builder clearHandshakeRequest() {
      if (handshakeRequestBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        handshakeRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     */
    public com.tabdisplay.client.proto.HandshakeRequest.Builder getHandshakeRequestBuilder() {
      return internalGetHandshakeRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeRequestOrBuilder getHandshakeRequestOrBuilder() {
      if ((payloadCase_ == 1) && (handshakeRequestBuilder_ != null)) {
        return handshakeRequestBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (com.tabdisplay.client.proto.HandshakeRequest) payload_;
        }
        return com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.HandshakeRequest handshake_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.HandshakeRequest, com.tabdisplay.client.proto.HandshakeRequest.Builder, com.tabdisplay.client.proto.HandshakeRequestOrBuilder> 
        internalGetHandshakeRequestFieldBuilder() {
      if (handshakeRequestBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance();
        }
        handshakeRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tabdisplay.client.proto.HandshakeRequest, com.tabdisplay.client.proto.HandshakeRequest.Builder, com.tabdisplay.client.proto.HandshakeRequestOrBuilder>(
                (com.tabdisplay.client.proto.HandshakeRequest) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();
      return handshakeRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.HandshakeResponse, com.tabdisplay.client.proto.HandshakeResponse.Builder, com.tabdisplay.client.proto.HandshakeResponseOrBuilder> handshakeResponseBuilder_;
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     * @return Whether the handshakeResponse field is set.
     */
    @java.lang.Override
    public boolean hasHandshakeResponse() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     * @return The handshakeResponse.
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeResponse getHandshakeResponse() {
      if (handshakeResponseBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (com.tabdisplay.client.proto.HandshakeResponse) payload_;
        }
        return com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return handshakeResponseBuilder_.getMessage();
        }
        return com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     */
    public Builder setHandshakeResponse(com.tabdisplay.client.proto.HandshakeResponse value) {
      if (handshakeResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        handshakeResponseBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     */
    public Builder setHandshakeResponse(
        com.tabdisplay.client.proto.HandshakeResponse.Builder builderForValue) {
      if (handshakeResponseBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        handshakeResponseBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     */
    public Builder mergeHandshakeResponse(com.tabdisplay.client.proto.HandshakeResponse value) {
      if (handshakeResponseBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance()) {
          payload_ = com.tabdisplay.client.proto.HandshakeResponse.newBuilder((com.tabdisplay.client.proto.HandshakeResponse) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          handshakeResponseBuilder_.mergeFrom(value);
        } else {
          handshakeResponseBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     */
    public Builder clearHandshakeResponse() {
      if (handshakeResponseBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        handshakeResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     */
    public com.tabdisplay.client.proto.HandshakeResponse.Builder getHandshakeResponseBuilder() {
      return internalGetHandshakeResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeResponseOrBuilder getHandshakeResponseOrBuilder() {
      if ((payloadCase_ == 2) && (handshakeResponseBuilder_ != null)) {
        return handshakeResponseBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (com.tabdisplay.client.proto.HandshakeResponse) payload_;
        }
        return com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.HandshakeResponse handshake_response = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.HandshakeResponse, com.tabdisplay.client.proto.HandshakeResponse.Builder, com.tabdisplay.client.proto.HandshakeResponseOrBuilder> 
        internalGetHandshakeResponseFieldBuilder() {
      if (handshakeResponseBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance();
        }
        handshakeResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tabdisplay.client.proto.HandshakeResponse, com.tabdisplay.client.proto.HandshakeResponse.Builder, com.tabdisplay.client.proto.HandshakeResponseOrBuilder>(
                (com.tabdisplay.client.proto.HandshakeResponse) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return handshakeResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.KeepAlive, com.tabdisplay.client.proto.KeepAlive.Builder, com.tabdisplay.client.proto.KeepAliveOrBuilder> keepAliveBuilder_;
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     * @return Whether the keepAlive field is set.
     */
    @java.lang.Override
    public boolean hasKeepAlive() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     * @return The keepAlive.
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.KeepAlive getKeepAlive() {
      if (keepAliveBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (com.tabdisplay.client.proto.KeepAlive) payload_;
        }
        return com.tabdisplay.client.proto.KeepAlive.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return keepAliveBuilder_.getMessage();
        }
        return com.tabdisplay.client.proto.KeepAlive.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     */
    public Builder setKeepAlive(com.tabdisplay.client.proto.KeepAlive value) {
      if (keepAliveBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        keepAliveBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     */
    public Builder setKeepAlive(
        com.tabdisplay.client.proto.KeepAlive.Builder builderForValue) {
      if (keepAliveBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        keepAliveBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     */
    public Builder mergeKeepAlive(com.tabdisplay.client.proto.KeepAlive value) {
      if (keepAliveBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != com.tabdisplay.client.proto.KeepAlive.getDefaultInstance()) {
          payload_ = com.tabdisplay.client.proto.KeepAlive.newBuilder((com.tabdisplay.client.proto.KeepAlive) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          keepAliveBuilder_.mergeFrom(value);
        } else {
          keepAliveBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     */
    public Builder clearKeepAlive() {
      if (keepAliveBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        keepAliveBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     */
    public com.tabdisplay.client.proto.KeepAlive.Builder getKeepAliveBuilder() {
      return internalGetKeepAliveFieldBuilder().getBuilder();
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.KeepAliveOrBuilder getKeepAliveOrBuilder() {
      if ((payloadCase_ == 3) && (keepAliveBuilder_ != null)) {
        return keepAliveBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (com.tabdisplay.client.proto.KeepAlive) payload_;
        }
        return com.tabdisplay.client.proto.KeepAlive.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.KeepAlive keep_alive = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.KeepAlive, com.tabdisplay.client.proto.KeepAlive.Builder, com.tabdisplay.client.proto.KeepAliveOrBuilder> 
        internalGetKeepAliveFieldBuilder() {
      if (keepAliveBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = com.tabdisplay.client.proto.KeepAlive.getDefaultInstance();
        }
        keepAliveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tabdisplay.client.proto.KeepAlive, com.tabdisplay.client.proto.KeepAlive.Builder, com.tabdisplay.client.proto.KeepAliveOrBuilder>(
                (com.tabdisplay.client.proto.KeepAlive) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return keepAliveBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.InputEvent, com.tabdisplay.client.proto.InputEvent.Builder, com.tabdisplay.client.proto.InputEventOrBuilder> inputEventBuilder_;
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     * @return Whether the inputEvent field is set.
     */
    @java.lang.Override
    public boolean hasInputEvent() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     * @return The inputEvent.
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.InputEvent getInputEvent() {
      if (inputEventBuilder_ == null) {
        if (payloadCase_ == 4) {
          return (com.tabdisplay.client.proto.InputEvent) payload_;
        }
        return com.tabdisplay.client.proto.InputEvent.getDefaultInstance();
      } else {
        if (payloadCase_ == 4) {
          return inputEventBuilder_.getMessage();
        }
        return com.tabdisplay.client.proto.InputEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     */
    public Builder setInputEvent(com.tabdisplay.client.proto.InputEvent value) {
      if (inputEventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        inputEventBuilder_.setMessage(value);
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     */
    public Builder setInputEvent(
        com.tabdisplay.client.proto.InputEvent.Builder builderForValue) {
      if (inputEventBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        inputEventBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     */
    public Builder mergeInputEvent(com.tabdisplay.client.proto.InputEvent value) {
      if (inputEventBuilder_ == null) {
        if (payloadCase_ == 4 &&
            payload_ != com.tabdisplay.client.proto.InputEvent.getDefaultInstance()) {
          payload_ = com.tabdisplay.client.proto.InputEvent.newBuilder((com.tabdisplay.client.proto.InputEvent) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 4) {
          inputEventBuilder_.mergeFrom(value);
        } else {
          inputEventBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     */
    public Builder clearInputEvent() {
      if (inputEventBuilder_ == null) {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
        }
        inputEventBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     */
    public com.tabdisplay.client.proto.InputEvent.Builder getInputEventBuilder() {
      return internalGetInputEventFieldBuilder().getBuilder();
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.InputEventOrBuilder getInputEventOrBuilder() {
      if ((payloadCase_ == 4) && (inputEventBuilder_ != null)) {
        return inputEventBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 4) {
          return (com.tabdisplay.client.proto.InputEvent) payload_;
        }
        return com.tabdisplay.client.proto.InputEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.InputEvent input_event = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.InputEvent, com.tabdisplay.client.proto.InputEvent.Builder, com.tabdisplay.client.proto.InputEventOrBuilder> 
        internalGetInputEventFieldBuilder() {
      if (inputEventBuilder_ == null) {
        if (!(payloadCase_ == 4)) {
          payload_ = com.tabdisplay.client.proto.InputEvent.getDefaultInstance();
        }
        inputEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tabdisplay.client.proto.InputEvent, com.tabdisplay.client.proto.InputEvent.Builder, com.tabdisplay.client.proto.InputEventOrBuilder>(
                (com.tabdisplay.client.proto.InputEvent) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 4;
      onChanged();
      return inputEventBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.TelemetryFeedback, com.tabdisplay.client.proto.TelemetryFeedback.Builder, com.tabdisplay.client.proto.TelemetryFeedbackOrBuilder> telemetryBuilder_;
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     * @return Whether the telemetry field is set.
     */
    @java.lang.Override
    public boolean hasTelemetry() {
      return payloadCase_ == 5;
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     * @return The telemetry.
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.TelemetryFeedback getTelemetry() {
      if (telemetryBuilder_ == null) {
        if (payloadCase_ == 5) {
          return (com.tabdisplay.client.proto.TelemetryFeedback) payload_;
        }
        return com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance();
      } else {
        if (payloadCase_ == 5) {
          return telemetryBuilder_.getMessage();
        }
        return com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     */
    public Builder setTelemetry(com.tabdisplay.client.proto.TelemetryFeedback value) {
      if (telemetryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        telemetryBuilder_.setMessage(value);
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     */
    public Builder setTelemetry(
        com.tabdisplay.client.proto.TelemetryFeedback.Builder builderForValue) {
      if (telemetryBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        telemetryBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     */
    public Builder mergeTelemetry(com.tabdisplay.client.proto.TelemetryFeedback value) {
      if (telemetryBuilder_ == null) {
        if (payloadCase_ == 5 &&
            payload_ != com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance()) {
          payload_ = com.tabdisplay.client.proto.TelemetryFeedback.newBuilder((com.tabdisplay.client.proto.TelemetryFeedback) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 5) {
          telemetryBuilder_.mergeFrom(value);
        } else {
          telemetryBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 5;
      return this;
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     */
    public Builder clearTelemetry() {
      if (telemetryBuilder_ == null) {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 5) {
          payloadCase_ = 0;
          payload_ = null;
        }
        telemetryBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     */
    public com.tabdisplay.client.proto.TelemetryFeedback.Builder getTelemetryBuilder() {
      return internalGetTelemetryFieldBuilder().getBuilder();
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.TelemetryFeedbackOrBuilder getTelemetryOrBuilder() {
      if ((payloadCase_ == 5) && (telemetryBuilder_ != null)) {
        return telemetryBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 5) {
          return (com.tabdisplay.client.proto.TelemetryFeedback) payload_;
        }
        return com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance();
      }
    }
    /**
     * <code>.tabdisplay.TelemetryFeedback telemetry = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.tabdisplay.client.proto.TelemetryFeedback, com.tabdisplay.client.proto.TelemetryFeedback.Builder, com.tabdisplay.client.proto.TelemetryFeedbackOrBuilder> 
        internalGetTelemetryFieldBuilder() {
      if (telemetryBuilder_ == null) {
        if (!(payloadCase_ == 5)) {
          payload_ = com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance();
        }
        telemetryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.tabdisplay.client.proto.TelemetryFeedback, com.tabdisplay.client.proto.TelemetryFeedback.Builder, com.tabdisplay.client.proto.TelemetryFeedbackOrBuilder>(
                (com.tabdisplay.client.proto.TelemetryFeedback) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 5;
      onChanged();
      return telemetryBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tabdisplay.ControlPacket)
  }

  // @@protoc_insertion_point(class_scope:tabdisplay.ControlPacket)
  private static final com.tabdisplay.client.proto.ControlPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tabdisplay.client.proto.ControlPacket();
  }

  public static com.tabdisplay.client.proto.ControlPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ControlPacket>
      PARSER = new com.google.protobuf.AbstractParser<ControlPacket>() {
    @java.lang.Override
    public ControlPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ControlPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ControlPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tabdisplay.client.proto.ControlPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

