// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

@com.google.protobuf.Generated
public final class Events extends com.google.protobuf.GeneratedFile {
  private Events() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Events");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tabdisplay_ControlPacket_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tabdisplay_ControlPacket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tabdisplay_HandshakeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tabdisplay_HandshakeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tabdisplay_HandshakeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tabdisplay_HandshakeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tabdisplay_KeepAlive_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tabdisplay_KeepAlive_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tabdisplay_InputEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tabdisplay_InputEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tabdisplay_TelemetryFeedback_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tabdisplay_TelemetryFeedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014events.proto\022\ntabdisplay\"\242\002\n\rControlPa" +
      "cket\0229\n\021handshake_request\030\001 \001(\0132\034.tabdis" +
      "play.HandshakeRequestH\000\022;\n\022handshake_res" +
      "ponse\030\002 \001(\0132\035.tabdisplay.HandshakeRespon" +
      "seH\000\022+\n\nkeep_alive\030\003 \001(\0132\025.tabdisplay.Ke" +
      "epAliveH\000\022-\n\013input_event\030\004 \001(\0132\026.tabdisp" +
      "lay.InputEventH\000\0222\n\ttelemetry\030\005 \001(\0132\035.ta" +
      "bdisplay.TelemetryFeedbackH\000B\t\n\007payload\"" +
      "u\n\020HandshakeRequest\022\032\n\022client_device_nam" +
      "e\030\001 \001(\t\022\027\n\017preferred_width\030\002 \001(\r\022\030\n\020pref" +
      "erred_height\030\003 \001(\r\022\022\n\ntarget_fps\030\004 \001(\r\"\240" +
      "\001\n\021HandshakeResponse\022\020\n\010accepted\030\001 \001(\010\022\023" +
      "\n\013server_name\030\002 \001(\t\022\027\n\017allocated_width\030\003" +
      " \001(\r\022\030\n\020allocated_height\030\004 \001(\r\022\026\n\016negoti" +
      "ated_fps\030\005 \001(\r\022\031\n\021video_stream_port\030\006 \001(" +
      "\r\"0\n\tKeepAlive\022\021\n\ttimestamp\030\001 \001(\004\022\020\n\010seq" +
      "uence\030\002 \001(\r\"\376\001\n\nInputEvent\0221\n\006action\030\001 \001" +
      "(\0162!.tabdisplay.InputEvent.ActionType\022\021\n" +
      "\tx_percent\030\002 \001(\002\022\021\n\ty_percent\030\003 \001(\002\022\026\n\016s" +
      "croll_delta_x\030\004 \001(\005\022\026\n\016scroll_delta_y\030\005 " +
      "\001(\005\022\025\n\rpointer_count\030\006 \001(\r\"P\n\nActionType" +
      "\022\017\n\013ACTION_DOWN\020\000\022\r\n\tACTION_UP\020\001\022\017\n\013ACTI" +
      "ON_MOVE\020\002\022\021\n\rACTION_SCROLL\020\003\"g\n\021Telemetr" +
      "yFeedback\022\030\n\020packet_loss_rate\030\001 \001(\002\022\031\n\021a" +
      "verage_jitter_ms\030\002 \001(\002\022\035\n\025end_to_end_lat" +
      "ency_ms\030\003 \001(\002B$\n\033com.tabdisplay.client.p" +
      "rotoP\001\272\002\002TDb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tabdisplay_ControlPacket_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_tabdisplay_ControlPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tabdisplay_ControlPacket_descriptor,
        new java.lang.String[] { "HandshakeRequest", "HandshakeResponse", "KeepAlive", "InputEvent", "Telemetry", "Payload", });
    internal_static_tabdisplay_HandshakeRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_tabdisplay_HandshakeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tabdisplay_HandshakeRequest_descriptor,
        new java.lang.String[] { "ClientDeviceName", "PreferredWidth", "PreferredHeight", "TargetFps", });
    internal_static_tabdisplay_HandshakeResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_tabdisplay_HandshakeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tabdisplay_HandshakeResponse_descriptor,
        new java.lang.String[] { "Accepted", "ServerName", "AllocatedWidth", "AllocatedHeight", "NegotiatedFps", "VideoStreamPort", });
    internal_static_tabdisplay_KeepAlive_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_tabdisplay_KeepAlive_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tabdisplay_KeepAlive_descriptor,
        new java.lang.String[] { "Timestamp", "Sequence", });
    internal_static_tabdisplay_InputEvent_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_tabdisplay_InputEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tabdisplay_InputEvent_descriptor,
        new java.lang.String[] { "Action", "XPercent", "YPercent", "ScrollDeltaX", "ScrollDeltaY", "PointerCount", });
    internal_static_tabdisplay_TelemetryFeedback_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_tabdisplay_TelemetryFeedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tabdisplay_TelemetryFeedback_descriptor,
        new java.lang.String[] { "PacketLossRate", "AverageJitterMs", "EndToEndLatencyMs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
