// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

/**
 * <pre>
 * Handshake Request from Client (Android) to Server (macOS)
 * </pre>
 *
 * Protobuf type {@code tabdisplay.HandshakeRequest}
 */
@com.google.protobuf.Generated
public final class HandshakeRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tabdisplay.HandshakeRequest)
    HandshakeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "HandshakeRequest");
  }
  // Use HandshakeRequest.newBuilder() to construct.
  private HandshakeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HandshakeRequest() {
    clientDeviceName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tabdisplay.client.proto.HandshakeRequest.class, com.tabdisplay.client.proto.HandshakeRequest.Builder.class);
  }

  public static final int CLIENT_DEVICE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientDeviceName_ = "";
  /**
   * <pre>
   * e.g. "Samsung Tab S6 Lite"
   * </pre>
   *
   * <code>string client_device_name = 1;</code>
   * @return The clientDeviceName.
   */
  @java.lang.Override
  public java.lang.String getClientDeviceName() {
    java.lang.Object ref = clientDeviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientDeviceName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g. "Samsung Tab S6 Lite"
   * </pre>
   *
   * <code>string client_device_name = 1;</code>
   * @return The bytes for clientDeviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientDeviceNameBytes() {
    java.lang.Object ref = clientDeviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientDeviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREFERRED_WIDTH_FIELD_NUMBER = 2;
  private int preferredWidth_ = 0;
  /**
   * <pre>
   * e.g. 1920
   * </pre>
   *
   * <code>uint32 preferred_width = 2;</code>
   * @return The preferredWidth.
   */
  @java.lang.Override
  public int getPreferredWidth() {
    return preferredWidth_;
  }

  public static final int PREFERRED_HEIGHT_FIELD_NUMBER = 3;
  private int preferredHeight_ = 0;
  /**
   * <pre>
   * e.g. 1200
   * </pre>
   *
   * <code>uint32 preferred_height = 3;</code>
   * @return The preferredHeight.
   */
  @java.lang.Override
  public int getPreferredHeight() {
    return preferredHeight_;
  }

  public static final int TARGET_FPS_FIELD_NUMBER = 4;
  private int targetFps_ = 0;
  /**
   * <pre>
   * e.g. 60
   * </pre>
   *
   * <code>uint32 target_fps = 4;</code>
   * @return The targetFps.
   */
  @java.lang.Override
  public int getTargetFps() {
    return targetFps_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientDeviceName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, clientDeviceName_);
    }
    if (preferredWidth_ != 0) {
      output.writeUInt32(2, preferredWidth_);
    }
    if (preferredHeight_ != 0) {
      output.writeUInt32(3, preferredHeight_);
    }
    if (targetFps_ != 0) {
      output.writeUInt32(4, targetFps_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientDeviceName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, clientDeviceName_);
    }
    if (preferredWidth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, preferredWidth_);
    }
    if (preferredHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, preferredHeight_);
    }
    if (targetFps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, targetFps_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tabdisplay.client.proto.HandshakeRequest)) {
      return super.equals(obj);
    }
    com.tabdisplay.client.proto.HandshakeRequest other = (com.tabdisplay.client.proto.HandshakeRequest) obj;

    if (!getClientDeviceName()
        .equals(other.getClientDeviceName())) return false;
    if (getPreferredWidth()
        != other.getPreferredWidth()) return false;
    if (getPreferredHeight()
        != other.getPreferredHeight()) return false;
    if (getTargetFps()
        != other.getTargetFps()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_DEVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientDeviceName().hashCode();
    hash = (37 * hash) + PREFERRED_WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getPreferredWidth();
    hash = (37 * hash) + PREFERRED_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getPreferredHeight();
    hash = (37 * hash) + TARGET_FPS_FIELD_NUMBER;
    hash = (53 * hash) + getTargetFps();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tabdisplay.client.proto.HandshakeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tabdisplay.client.proto.HandshakeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.HandshakeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tabdisplay.client.proto.HandshakeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Handshake Request from Client (Android) to Server (macOS)
   * </pre>
   *
   * Protobuf type {@code tabdisplay.HandshakeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tabdisplay.HandshakeRequest)
      com.tabdisplay.client.proto.HandshakeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tabdisplay.client.proto.HandshakeRequest.class, com.tabdisplay.client.proto.HandshakeRequest.Builder.class);
    }

    // Construct using com.tabdisplay.client.proto.HandshakeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      clientDeviceName_ = "";
      preferredWidth_ = 0;
      preferredHeight_ = 0;
      targetFps_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeRequest_descriptor;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeRequest getDefaultInstanceForType() {
      return com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeRequest build() {
      com.tabdisplay.client.proto.HandshakeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeRequest buildPartial() {
      com.tabdisplay.client.proto.HandshakeRequest result = new com.tabdisplay.client.proto.HandshakeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tabdisplay.client.proto.HandshakeRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.clientDeviceName_ = clientDeviceName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.preferredWidth_ = preferredWidth_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.preferredHeight_ = preferredHeight_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.targetFps_ = targetFps_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tabdisplay.client.proto.HandshakeRequest) {
        return mergeFrom((com.tabdisplay.client.proto.HandshakeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tabdisplay.client.proto.HandshakeRequest other) {
      if (other == com.tabdisplay.client.proto.HandshakeRequest.getDefaultInstance()) return this;
      if (!other.getClientDeviceName().isEmpty()) {
        clientDeviceName_ = other.clientDeviceName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPreferredWidth() != 0) {
        setPreferredWidth(other.getPreferredWidth());
      }
      if (other.getPreferredHeight() != 0) {
        setPreferredHeight(other.getPreferredHeight());
      }
      if (other.getTargetFps() != 0) {
        setTargetFps(other.getTargetFps());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              clientDeviceName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              preferredWidth_ = input.readUInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              preferredHeight_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              targetFps_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object clientDeviceName_ = "";
    /**
     * <pre>
     * e.g. "Samsung Tab S6 Lite"
     * </pre>
     *
     * <code>string client_device_name = 1;</code>
     * @return The clientDeviceName.
     */
    public java.lang.String getClientDeviceName() {
      java.lang.Object ref = clientDeviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientDeviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. "Samsung Tab S6 Lite"
     * </pre>
     *
     * <code>string client_device_name = 1;</code>
     * @return The bytes for clientDeviceName.
     */
    public com.google.protobuf.ByteString
        getClientDeviceNameBytes() {
      java.lang.Object ref = clientDeviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientDeviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. "Samsung Tab S6 Lite"
     * </pre>
     *
     * <code>string client_device_name = 1;</code>
     * @param value The clientDeviceName to set.
     * @return This builder for chaining.
     */
    public Builder setClientDeviceName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientDeviceName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "Samsung Tab S6 Lite"
     * </pre>
     *
     * <code>string client_device_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientDeviceName() {
      clientDeviceName_ = getDefaultInstance().getClientDeviceName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "Samsung Tab S6 Lite"
     * </pre>
     *
     * <code>string client_device_name = 1;</code>
     * @param value The bytes for clientDeviceName to set.
     * @return This builder for chaining.
     */
    public Builder setClientDeviceNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientDeviceName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int preferredWidth_ ;
    /**
     * <pre>
     * e.g. 1920
     * </pre>
     *
     * <code>uint32 preferred_width = 2;</code>
     * @return The preferredWidth.
     */
    @java.lang.Override
    public int getPreferredWidth() {
      return preferredWidth_;
    }
    /**
     * <pre>
     * e.g. 1920
     * </pre>
     *
     * <code>uint32 preferred_width = 2;</code>
     * @param value The preferredWidth to set.
     * @return This builder for chaining.
     */
    public Builder setPreferredWidth(int value) {

      preferredWidth_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. 1920
     * </pre>
     *
     * <code>uint32 preferred_width = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferredWidth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      preferredWidth_ = 0;
      onChanged();
      return this;
    }

    private int preferredHeight_ ;
    /**
     * <pre>
     * e.g. 1200
     * </pre>
     *
     * <code>uint32 preferred_height = 3;</code>
     * @return The preferredHeight.
     */
    @java.lang.Override
    public int getPreferredHeight() {
      return preferredHeight_;
    }
    /**
     * <pre>
     * e.g. 1200
     * </pre>
     *
     * <code>uint32 preferred_height = 3;</code>
     * @param value The preferredHeight to set.
     * @return This builder for chaining.
     */
    public Builder setPreferredHeight(int value) {

      preferredHeight_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. 1200
     * </pre>
     *
     * <code>uint32 preferred_height = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferredHeight() {
      bitField0_ = (bitField0_ & ~0x00000004);
      preferredHeight_ = 0;
      onChanged();
      return this;
    }

    private int targetFps_ ;
    /**
     * <pre>
     * e.g. 60
     * </pre>
     *
     * <code>uint32 target_fps = 4;</code>
     * @return The targetFps.
     */
    @java.lang.Override
    public int getTargetFps() {
      return targetFps_;
    }
    /**
     * <pre>
     * e.g. 60
     * </pre>
     *
     * <code>uint32 target_fps = 4;</code>
     * @param value The targetFps to set.
     * @return This builder for chaining.
     */
    public Builder setTargetFps(int value) {

      targetFps_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. 60
     * </pre>
     *
     * <code>uint32 target_fps = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetFps() {
      bitField0_ = (bitField0_ & ~0x00000008);
      targetFps_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tabdisplay.HandshakeRequest)
  }

  // @@protoc_insertion_point(class_scope:tabdisplay.HandshakeRequest)
  private static final com.tabdisplay.client.proto.HandshakeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tabdisplay.client.proto.HandshakeRequest();
  }

  public static com.tabdisplay.client.proto.HandshakeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandshakeRequest>
      PARSER = new com.google.protobuf.AbstractParser<HandshakeRequest>() {
    @java.lang.Override
    public HandshakeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HandshakeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandshakeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tabdisplay.client.proto.HandshakeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

