// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/proto/events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

@com.google.protobuf.Generated
public interface HandshakeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tabdisplay.HandshakeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <pre>
   * e.g. "MacBook Air"
   * </pre>
   *
   * <code>string server_name = 2;</code>
   * @return The serverName.
   */
  java.lang.String getServerName();
  /**
   * <pre>
   * e.g. "MacBook Air"
   * </pre>
   *
   * <code>string server_name = 2;</code>
   * @return The bytes for serverName.
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <pre>
   * Actual virtual display resolution width
   * </pre>
   *
   * <code>uint32 allocated_width = 3;</code>
   * @return The allocatedWidth.
   */
  int getAllocatedWidth();

  /**
   * <pre>
   * Actual virtual display resolution height
   * </pre>
   *
   * <code>uint32 allocated_height = 4;</code>
   * @return The allocatedHeight.
   */
  int getAllocatedHeight();

  /**
   * <code>uint32 negotiated_fps = 5;</code>
   * @return The negotiatedFps.
   */
  int getNegotiatedFps();

  /**
   * <pre>
   * UDP/TCP Port for video transmission
   * </pre>
   *
   * <code>uint32 video_stream_port = 6;</code>
   * @return The videoStreamPort.
   */
  int getVideoStreamPort();

  /**
   * <pre>
   * Transport protocol for video stream
   * </pre>
   *
   * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
   * @return The enum numeric value on the wire for videoTransport.
   */
  int getVideoTransportValue();
  /**
   * <pre>
   * Transport protocol for video stream
   * </pre>
   *
   * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
   * @return The videoTransport.
   */
  com.tabdisplay.client.proto.VideoTransport getVideoTransport();
}
