// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/proto/events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

@com.google.protobuf.Generated
public interface HandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tabdisplay.HandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. "Samsung Tab S6 Lite"
   * </pre>
   *
   * <code>string client_device_name = 1;</code>
   * @return The clientDeviceName.
   */
  java.lang.String getClientDeviceName();
  /**
   * <pre>
   * e.g. "Samsung Tab S6 Lite"
   * </pre>
   *
   * <code>string client_device_name = 1;</code>
   * @return The bytes for clientDeviceName.
   */
  com.google.protobuf.ByteString
      getClientDeviceNameBytes();

  /**
   * <pre>
   * e.g. 1920
   * </pre>
   *
   * <code>uint32 preferred_width = 2;</code>
   * @return The preferredWidth.
   */
  int getPreferredWidth();

  /**
   * <pre>
   * e.g. 1200
   * </pre>
   *
   * <code>uint32 preferred_height = 3;</code>
   * @return The preferredHeight.
   */
  int getPreferredHeight();

  /**
   * <pre>
   * e.g. 60
   * </pre>
   *
   * <code>uint32 target_fps = 4;</code>
   * @return The targetFps.
   */
  int getTargetFps();
}
