// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/proto/events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

/**
 * <pre>
 * Handshake Response from Server (macOS) to Client (Android)
 * </pre>
 *
 * Protobuf type {@code tabdisplay.HandshakeResponse}
 */
@com.google.protobuf.Generated
public final class HandshakeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tabdisplay.HandshakeResponse)
    HandshakeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "HandshakeResponse");
  }
  // Use HandshakeResponse.newBuilder() to construct.
  private HandshakeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HandshakeResponse() {
    serverName_ = "";
    videoTransport_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tabdisplay.client.proto.HandshakeResponse.class, com.tabdisplay.client.proto.HandshakeResponse.Builder.class);
  }

  public static final int ACCEPTED_FIELD_NUMBER = 1;
  private boolean accepted_ = false;
  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  @java.lang.Override
  public boolean getAccepted() {
    return accepted_;
  }

  public static final int SERVER_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serverName_ = "";
  /**
   * <pre>
   * e.g. "MacBook Air"
   * </pre>
   *
   * <code>string server_name = 2;</code>
   * @return The serverName.
   */
  @java.lang.Override
  public java.lang.String getServerName() {
    java.lang.Object ref = serverName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serverName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g. "MacBook Air"
   * </pre>
   *
   * <code>string server_name = 2;</code>
   * @return The bytes for serverName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServerNameBytes() {
    java.lang.Object ref = serverName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serverName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLOCATED_WIDTH_FIELD_NUMBER = 3;
  private int allocatedWidth_ = 0;
  /**
   * <pre>
   * Actual virtual display resolution width
   * </pre>
   *
   * <code>uint32 allocated_width = 3;</code>
   * @return The allocatedWidth.
   */
  @java.lang.Override
  public int getAllocatedWidth() {
    return allocatedWidth_;
  }

  public static final int ALLOCATED_HEIGHT_FIELD_NUMBER = 4;
  private int allocatedHeight_ = 0;
  /**
   * <pre>
   * Actual virtual display resolution height
   * </pre>
   *
   * <code>uint32 allocated_height = 4;</code>
   * @return The allocatedHeight.
   */
  @java.lang.Override
  public int getAllocatedHeight() {
    return allocatedHeight_;
  }

  public static final int NEGOTIATED_FPS_FIELD_NUMBER = 5;
  private int negotiatedFps_ = 0;
  /**
   * <code>uint32 negotiated_fps = 5;</code>
   * @return The negotiatedFps.
   */
  @java.lang.Override
  public int getNegotiatedFps() {
    return negotiatedFps_;
  }

  public static final int VIDEO_STREAM_PORT_FIELD_NUMBER = 6;
  private int videoStreamPort_ = 0;
  /**
   * <pre>
   * UDP/TCP Port for video transmission
   * </pre>
   *
   * <code>uint32 video_stream_port = 6;</code>
   * @return The videoStreamPort.
   */
  @java.lang.Override
  public int getVideoStreamPort() {
    return videoStreamPort_;
  }

  public static final int VIDEO_TRANSPORT_FIELD_NUMBER = 7;
  private int videoTransport_ = 0;
  /**
   * <pre>
   * Transport protocol for video stream
   * </pre>
   *
   * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
   * @return The enum numeric value on the wire for videoTransport.
   */
  @java.lang.Override public int getVideoTransportValue() {
    return videoTransport_;
  }
  /**
   * <pre>
   * Transport protocol for video stream
   * </pre>
   *
   * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
   * @return The videoTransport.
   */
  @java.lang.Override public com.tabdisplay.client.proto.VideoTransport getVideoTransport() {
    com.tabdisplay.client.proto.VideoTransport result = com.tabdisplay.client.proto.VideoTransport.forNumber(videoTransport_);
    return result == null ? com.tabdisplay.client.proto.VideoTransport.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (accepted_ != false) {
      output.writeBool(1, accepted_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, serverName_);
    }
    if (allocatedWidth_ != 0) {
      output.writeUInt32(3, allocatedWidth_);
    }
    if (allocatedHeight_ != 0) {
      output.writeUInt32(4, allocatedHeight_);
    }
    if (negotiatedFps_ != 0) {
      output.writeUInt32(5, negotiatedFps_);
    }
    if (videoStreamPort_ != 0) {
      output.writeUInt32(6, videoStreamPort_);
    }
    if (videoTransport_ != com.tabdisplay.client.proto.VideoTransport.UDP.getNumber()) {
      output.writeEnum(7, videoTransport_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (accepted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, accepted_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serverName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, serverName_);
    }
    if (allocatedWidth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, allocatedWidth_);
    }
    if (allocatedHeight_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, allocatedHeight_);
    }
    if (negotiatedFps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, negotiatedFps_);
    }
    if (videoStreamPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, videoStreamPort_);
    }
    if (videoTransport_ != com.tabdisplay.client.proto.VideoTransport.UDP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, videoTransport_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tabdisplay.client.proto.HandshakeResponse)) {
      return super.equals(obj);
    }
    com.tabdisplay.client.proto.HandshakeResponse other = (com.tabdisplay.client.proto.HandshakeResponse) obj;

    if (getAccepted()
        != other.getAccepted()) return false;
    if (!getServerName()
        .equals(other.getServerName())) return false;
    if (getAllocatedWidth()
        != other.getAllocatedWidth()) return false;
    if (getAllocatedHeight()
        != other.getAllocatedHeight()) return false;
    if (getNegotiatedFps()
        != other.getNegotiatedFps()) return false;
    if (getVideoStreamPort()
        != other.getVideoStreamPort()) return false;
    if (videoTransport_ != other.videoTransport_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCEPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAccepted());
    hash = (37 * hash) + SERVER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServerName().hashCode();
    hash = (37 * hash) + ALLOCATED_WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getAllocatedWidth();
    hash = (37 * hash) + ALLOCATED_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getAllocatedHeight();
    hash = (37 * hash) + NEGOTIATED_FPS_FIELD_NUMBER;
    hash = (53 * hash) + getNegotiatedFps();
    hash = (37 * hash) + VIDEO_STREAM_PORT_FIELD_NUMBER;
    hash = (53 * hash) + getVideoStreamPort();
    hash = (37 * hash) + VIDEO_TRANSPORT_FIELD_NUMBER;
    hash = (53 * hash) + videoTransport_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tabdisplay.client.proto.HandshakeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tabdisplay.client.proto.HandshakeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.HandshakeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tabdisplay.client.proto.HandshakeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Handshake Response from Server (macOS) to Client (Android)
   * </pre>
   *
   * Protobuf type {@code tabdisplay.HandshakeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tabdisplay.HandshakeResponse)
      com.tabdisplay.client.proto.HandshakeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tabdisplay.client.proto.HandshakeResponse.class, com.tabdisplay.client.proto.HandshakeResponse.Builder.class);
    }

    // Construct using com.tabdisplay.client.proto.HandshakeResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      accepted_ = false;
      serverName_ = "";
      allocatedWidth_ = 0;
      allocatedHeight_ = 0;
      negotiatedFps_ = 0;
      videoStreamPort_ = 0;
      videoTransport_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_HandshakeResponse_descriptor;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeResponse getDefaultInstanceForType() {
      return com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeResponse build() {
      com.tabdisplay.client.proto.HandshakeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.HandshakeResponse buildPartial() {
      com.tabdisplay.client.proto.HandshakeResponse result = new com.tabdisplay.client.proto.HandshakeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tabdisplay.client.proto.HandshakeResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.accepted_ = accepted_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serverName_ = serverName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.allocatedWidth_ = allocatedWidth_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.allocatedHeight_ = allocatedHeight_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.negotiatedFps_ = negotiatedFps_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.videoStreamPort_ = videoStreamPort_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.videoTransport_ = videoTransport_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tabdisplay.client.proto.HandshakeResponse) {
        return mergeFrom((com.tabdisplay.client.proto.HandshakeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tabdisplay.client.proto.HandshakeResponse other) {
      if (other == com.tabdisplay.client.proto.HandshakeResponse.getDefaultInstance()) return this;
      if (other.getAccepted() != false) {
        setAccepted(other.getAccepted());
      }
      if (!other.getServerName().isEmpty()) {
        serverName_ = other.serverName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAllocatedWidth() != 0) {
        setAllocatedWidth(other.getAllocatedWidth());
      }
      if (other.getAllocatedHeight() != 0) {
        setAllocatedHeight(other.getAllocatedHeight());
      }
      if (other.getNegotiatedFps() != 0) {
        setNegotiatedFps(other.getNegotiatedFps());
      }
      if (other.getVideoStreamPort() != 0) {
        setVideoStreamPort(other.getVideoStreamPort());
      }
      if (other.videoTransport_ != 0) {
        setVideoTransportValue(other.getVideoTransportValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              accepted_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              serverName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              allocatedWidth_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              allocatedHeight_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              negotiatedFps_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              videoStreamPort_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              videoTransport_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean accepted_ ;
    /**
     * <code>bool accepted = 1;</code>
     * @return The accepted.
     */
    @java.lang.Override
    public boolean getAccepted() {
      return accepted_;
    }
    /**
     * <code>bool accepted = 1;</code>
     * @param value The accepted to set.
     * @return This builder for chaining.
     */
    public Builder setAccepted(boolean value) {

      accepted_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool accepted = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccepted() {
      bitField0_ = (bitField0_ & ~0x00000001);
      accepted_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object serverName_ = "";
    /**
     * <pre>
     * e.g. "MacBook Air"
     * </pre>
     *
     * <code>string server_name = 2;</code>
     * @return The serverName.
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serverName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. "MacBook Air"
     * </pre>
     *
     * <code>string server_name = 2;</code>
     * @return The bytes for serverName.
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. "MacBook Air"
     * </pre>
     *
     * <code>string server_name = 2;</code>
     * @param value The serverName to set.
     * @return This builder for chaining.
     */
    public Builder setServerName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serverName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "MacBook Air"
     * </pre>
     *
     * <code>string server_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerName() {
      serverName_ = getDefaultInstance().getServerName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "MacBook Air"
     * </pre>
     *
     * <code>string server_name = 2;</code>
     * @param value The bytes for serverName to set.
     * @return This builder for chaining.
     */
    public Builder setServerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serverName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int allocatedWidth_ ;
    /**
     * <pre>
     * Actual virtual display resolution width
     * </pre>
     *
     * <code>uint32 allocated_width = 3;</code>
     * @return The allocatedWidth.
     */
    @java.lang.Override
    public int getAllocatedWidth() {
      return allocatedWidth_;
    }
    /**
     * <pre>
     * Actual virtual display resolution width
     * </pre>
     *
     * <code>uint32 allocated_width = 3;</code>
     * @param value The allocatedWidth to set.
     * @return This builder for chaining.
     */
    public Builder setAllocatedWidth(int value) {

      allocatedWidth_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Actual virtual display resolution width
     * </pre>
     *
     * <code>uint32 allocated_width = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllocatedWidth() {
      bitField0_ = (bitField0_ & ~0x00000004);
      allocatedWidth_ = 0;
      onChanged();
      return this;
    }

    private int allocatedHeight_ ;
    /**
     * <pre>
     * Actual virtual display resolution height
     * </pre>
     *
     * <code>uint32 allocated_height = 4;</code>
     * @return The allocatedHeight.
     */
    @java.lang.Override
    public int getAllocatedHeight() {
      return allocatedHeight_;
    }
    /**
     * <pre>
     * Actual virtual display resolution height
     * </pre>
     *
     * <code>uint32 allocated_height = 4;</code>
     * @param value The allocatedHeight to set.
     * @return This builder for chaining.
     */
    public Builder setAllocatedHeight(int value) {

      allocatedHeight_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Actual virtual display resolution height
     * </pre>
     *
     * <code>uint32 allocated_height = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllocatedHeight() {
      bitField0_ = (bitField0_ & ~0x00000008);
      allocatedHeight_ = 0;
      onChanged();
      return this;
    }

    private int negotiatedFps_ ;
    /**
     * <code>uint32 negotiated_fps = 5;</code>
     * @return The negotiatedFps.
     */
    @java.lang.Override
    public int getNegotiatedFps() {
      return negotiatedFps_;
    }
    /**
     * <code>uint32 negotiated_fps = 5;</code>
     * @param value The negotiatedFps to set.
     * @return This builder for chaining.
     */
    public Builder setNegotiatedFps(int value) {

      negotiatedFps_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 negotiated_fps = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNegotiatedFps() {
      bitField0_ = (bitField0_ & ~0x00000010);
      negotiatedFps_ = 0;
      onChanged();
      return this;
    }

    private int videoStreamPort_ ;
    /**
     * <pre>
     * UDP/TCP Port for video transmission
     * </pre>
     *
     * <code>uint32 video_stream_port = 6;</code>
     * @return The videoStreamPort.
     */
    @java.lang.Override
    public int getVideoStreamPort() {
      return videoStreamPort_;
    }
    /**
     * <pre>
     * UDP/TCP Port for video transmission
     * </pre>
     *
     * <code>uint32 video_stream_port = 6;</code>
     * @param value The videoStreamPort to set.
     * @return This builder for chaining.
     */
    public Builder setVideoStreamPort(int value) {

      videoStreamPort_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * UDP/TCP Port for video transmission
     * </pre>
     *
     * <code>uint32 video_stream_port = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoStreamPort() {
      bitField0_ = (bitField0_ & ~0x00000020);
      videoStreamPort_ = 0;
      onChanged();
      return this;
    }

    private int videoTransport_ = 0;
    /**
     * <pre>
     * Transport protocol for video stream
     * </pre>
     *
     * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
     * @return The enum numeric value on the wire for videoTransport.
     */
    @java.lang.Override public int getVideoTransportValue() {
      return videoTransport_;
    }
    /**
     * <pre>
     * Transport protocol for video stream
     * </pre>
     *
     * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
     * @param value The enum numeric value on the wire for videoTransport to set.
     * @return This builder for chaining.
     */
    public Builder setVideoTransportValue(int value) {
      videoTransport_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transport protocol for video stream
     * </pre>
     *
     * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
     * @return The videoTransport.
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.VideoTransport getVideoTransport() {
      com.tabdisplay.client.proto.VideoTransport result = com.tabdisplay.client.proto.VideoTransport.forNumber(videoTransport_);
      return result == null ? com.tabdisplay.client.proto.VideoTransport.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Transport protocol for video stream
     * </pre>
     *
     * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
     * @param value The videoTransport to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setVideoTransport(com.tabdisplay.client.proto.VideoTransport value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000040;
      videoTransport_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Transport protocol for video stream
     * </pre>
     *
     * <code>.tabdisplay.VideoTransport video_transport = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearVideoTransport() {
      bitField0_ = (bitField0_ & ~0x00000040);
      videoTransport_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tabdisplay.HandshakeResponse)
  }

  // @@protoc_insertion_point(class_scope:tabdisplay.HandshakeResponse)
  private static final com.tabdisplay.client.proto.HandshakeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tabdisplay.client.proto.HandshakeResponse();
  }

  public static com.tabdisplay.client.proto.HandshakeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandshakeResponse>
      PARSER = new com.google.protobuf.AbstractParser<HandshakeResponse>() {
    @java.lang.Override
    public HandshakeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HandshakeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandshakeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tabdisplay.client.proto.HandshakeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

