// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/proto/events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

/**
 * <pre>
 * User Input Event forwarded from Android Client to macOS Server
 * </pre>
 *
 * Protobuf type {@code tabdisplay.InputEvent}
 */
@com.google.protobuf.Generated
public final class InputEvent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tabdisplay.InputEvent)
    InputEventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "InputEvent");
  }
  // Use InputEvent.newBuilder() to construct.
  private InputEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InputEvent() {
    action_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_InputEvent_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_InputEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_InputEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tabdisplay.client.proto.InputEvent.class, com.tabdisplay.client.proto.InputEvent.Builder.class);
  }

  /**
   * Protobuf enum {@code tabdisplay.InputEvent.ActionType}
   */
  public enum ActionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACTION_DOWN = 0;</code>
     */
    ACTION_DOWN(0),
    /**
     * <code>ACTION_UP = 1;</code>
     */
    ACTION_UP(1),
    /**
     * <code>ACTION_MOVE = 2;</code>
     */
    ACTION_MOVE(2),
    /**
     * <code>ACTION_SCROLL = 3;</code>
     */
    ACTION_SCROLL(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "ActionType");
    }
    /**
     * <code>ACTION_DOWN = 0;</code>
     */
    public static final int ACTION_DOWN_VALUE = 0;
    /**
     * <code>ACTION_UP = 1;</code>
     */
    public static final int ACTION_UP_VALUE = 1;
    /**
     * <code>ACTION_MOVE = 2;</code>
     */
    public static final int ACTION_MOVE_VALUE = 2;
    /**
     * <code>ACTION_SCROLL = 3;</code>
     */
    public static final int ACTION_SCROLL_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ActionType forNumber(int value) {
      switch (value) {
        case 0: return ACTION_DOWN;
        case 1: return ACTION_UP;
        case 2: return ACTION_MOVE;
        case 3: return ACTION_SCROLL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
            public ActionType findValueByNumber(int number) {
              return ActionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tabdisplay.client.proto.InputEvent.getDescriptor().getEnumType(0);
    }

    private static final ActionType[] VALUES = values();

    public static ActionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ActionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tabdisplay.InputEvent.ActionType)
  }

  public static final int ACTION_FIELD_NUMBER = 1;
  private int action_ = 0;
  /**
   * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  @java.lang.Override public int getActionValue() {
    return action_;
  }
  /**
   * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
   * @return The action.
   */
  @java.lang.Override public com.tabdisplay.client.proto.InputEvent.ActionType getAction() {
    com.tabdisplay.client.proto.InputEvent.ActionType result = com.tabdisplay.client.proto.InputEvent.ActionType.forNumber(action_);
    return result == null ? com.tabdisplay.client.proto.InputEvent.ActionType.UNRECOGNIZED : result;
  }

  public static final int X_PERCENT_FIELD_NUMBER = 2;
  private float xPercent_ = 0F;
  /**
   * <pre>
   * Horizontal position [0.0 - 1.0]
   * </pre>
   *
   * <code>float x_percent = 2;</code>
   * @return The xPercent.
   */
  @java.lang.Override
  public float getXPercent() {
    return xPercent_;
  }

  public static final int Y_PERCENT_FIELD_NUMBER = 3;
  private float yPercent_ = 0F;
  /**
   * <pre>
   * Vertical position [0.0 - 1.0]
   * </pre>
   *
   * <code>float y_percent = 3;</code>
   * @return The yPercent.
   */
  @java.lang.Override
  public float getYPercent() {
    return yPercent_;
  }

  public static final int SCROLL_DELTA_X_FIELD_NUMBER = 4;
  private int scrollDeltaX_ = 0;
  /**
   * <pre>
   * Scroll offsets (only for ACTION_SCROLL)
   * </pre>
   *
   * <code>int32 scroll_delta_x = 4;</code>
   * @return The scrollDeltaX.
   */
  @java.lang.Override
  public int getScrollDeltaX() {
    return scrollDeltaX_;
  }

  public static final int SCROLL_DELTA_Y_FIELD_NUMBER = 5;
  private int scrollDeltaY_ = 0;
  /**
   * <code>int32 scroll_delta_y = 5;</code>
   * @return The scrollDeltaY.
   */
  @java.lang.Override
  public int getScrollDeltaY() {
    return scrollDeltaY_;
  }

  public static final int POINTER_COUNT_FIELD_NUMBER = 6;
  private int pointerCount_ = 0;
  /**
   * <pre>
   * For multi-touch gestures
   * </pre>
   *
   * <code>uint32 pointer_count = 6;</code>
   * @return The pointerCount.
   */
  @java.lang.Override
  public int getPointerCount() {
    return pointerCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (action_ != com.tabdisplay.client.proto.InputEvent.ActionType.ACTION_DOWN.getNumber()) {
      output.writeEnum(1, action_);
    }
    if (java.lang.Float.floatToRawIntBits(xPercent_) != 0) {
      output.writeFloat(2, xPercent_);
    }
    if (java.lang.Float.floatToRawIntBits(yPercent_) != 0) {
      output.writeFloat(3, yPercent_);
    }
    if (scrollDeltaX_ != 0) {
      output.writeInt32(4, scrollDeltaX_);
    }
    if (scrollDeltaY_ != 0) {
      output.writeInt32(5, scrollDeltaY_);
    }
    if (pointerCount_ != 0) {
      output.writeUInt32(6, pointerCount_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (action_ != com.tabdisplay.client.proto.InputEvent.ActionType.ACTION_DOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, action_);
    }
    if (java.lang.Float.floatToRawIntBits(xPercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, xPercent_);
    }
    if (java.lang.Float.floatToRawIntBits(yPercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, yPercent_);
    }
    if (scrollDeltaX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, scrollDeltaX_);
    }
    if (scrollDeltaY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, scrollDeltaY_);
    }
    if (pointerCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, pointerCount_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tabdisplay.client.proto.InputEvent)) {
      return super.equals(obj);
    }
    com.tabdisplay.client.proto.InputEvent other = (com.tabdisplay.client.proto.InputEvent) obj;

    if (action_ != other.action_) return false;
    if (java.lang.Float.floatToIntBits(getXPercent())
        != java.lang.Float.floatToIntBits(
            other.getXPercent())) return false;
    if (java.lang.Float.floatToIntBits(getYPercent())
        != java.lang.Float.floatToIntBits(
            other.getYPercent())) return false;
    if (getScrollDeltaX()
        != other.getScrollDeltaX()) return false;
    if (getScrollDeltaY()
        != other.getScrollDeltaY()) return false;
    if (getPointerCount()
        != other.getPointerCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + action_;
    hash = (37 * hash) + X_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getXPercent());
    hash = (37 * hash) + Y_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getYPercent());
    hash = (37 * hash) + SCROLL_DELTA_X_FIELD_NUMBER;
    hash = (53 * hash) + getScrollDeltaX();
    hash = (37 * hash) + SCROLL_DELTA_Y_FIELD_NUMBER;
    hash = (53 * hash) + getScrollDeltaY();
    hash = (37 * hash) + POINTER_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getPointerCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tabdisplay.client.proto.InputEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tabdisplay.client.proto.InputEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.InputEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tabdisplay.client.proto.InputEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * User Input Event forwarded from Android Client to macOS Server
   * </pre>
   *
   * Protobuf type {@code tabdisplay.InputEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tabdisplay.InputEvent)
      com.tabdisplay.client.proto.InputEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_InputEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_InputEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tabdisplay.client.proto.InputEvent.class, com.tabdisplay.client.proto.InputEvent.Builder.class);
    }

    // Construct using com.tabdisplay.client.proto.InputEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      action_ = 0;
      xPercent_ = 0F;
      yPercent_ = 0F;
      scrollDeltaX_ = 0;
      scrollDeltaY_ = 0;
      pointerCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_InputEvent_descriptor;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.InputEvent getDefaultInstanceForType() {
      return com.tabdisplay.client.proto.InputEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.InputEvent build() {
      com.tabdisplay.client.proto.InputEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.InputEvent buildPartial() {
      com.tabdisplay.client.proto.InputEvent result = new com.tabdisplay.client.proto.InputEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tabdisplay.client.proto.InputEvent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.action_ = action_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.xPercent_ = xPercent_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.yPercent_ = yPercent_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.scrollDeltaX_ = scrollDeltaX_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.scrollDeltaY_ = scrollDeltaY_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.pointerCount_ = pointerCount_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tabdisplay.client.proto.InputEvent) {
        return mergeFrom((com.tabdisplay.client.proto.InputEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tabdisplay.client.proto.InputEvent other) {
      if (other == com.tabdisplay.client.proto.InputEvent.getDefaultInstance()) return this;
      if (other.action_ != 0) {
        setActionValue(other.getActionValue());
      }
      if (java.lang.Float.floatToRawIntBits(other.getXPercent()) != 0) {
        setXPercent(other.getXPercent());
      }
      if (java.lang.Float.floatToRawIntBits(other.getYPercent()) != 0) {
        setYPercent(other.getYPercent());
      }
      if (other.getScrollDeltaX() != 0) {
        setScrollDeltaX(other.getScrollDeltaX());
      }
      if (other.getScrollDeltaY() != 0) {
        setScrollDeltaY(other.getScrollDeltaY());
      }
      if (other.getPointerCount() != 0) {
        setPointerCount(other.getPointerCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              action_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 21: {
              xPercent_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              yPercent_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 32: {
              scrollDeltaX_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              scrollDeltaY_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              pointerCount_ = input.readUInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int action_ = 0;
    /**
     * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
     * @param value The enum numeric value on the wire for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionValue(int value) {
      action_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
     * @return The action.
     */
    @java.lang.Override
    public com.tabdisplay.client.proto.InputEvent.ActionType getAction() {
      com.tabdisplay.client.proto.InputEvent.ActionType result = com.tabdisplay.client.proto.InputEvent.ActionType.forNumber(action_);
      return result == null ? com.tabdisplay.client.proto.InputEvent.ActionType.UNRECOGNIZED : result;
    }
    /**
     * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
     * @param value The action to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setAction(com.tabdisplay.client.proto.InputEvent.ActionType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      action_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000001);
      action_ = 0;
      onChanged();
      return this;
    }

    private float xPercent_ ;
    /**
     * <pre>
     * Horizontal position [0.0 - 1.0]
     * </pre>
     *
     * <code>float x_percent = 2;</code>
     * @return The xPercent.
     */
    @java.lang.Override
    public float getXPercent() {
      return xPercent_;
    }
    /**
     * <pre>
     * Horizontal position [0.0 - 1.0]
     * </pre>
     *
     * <code>float x_percent = 2;</code>
     * @param value The xPercent to set.
     * @return This builder for chaining.
     */
    public Builder setXPercent(float value) {

      xPercent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Horizontal position [0.0 - 1.0]
     * </pre>
     *
     * <code>float x_percent = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearXPercent() {
      bitField0_ = (bitField0_ & ~0x00000002);
      xPercent_ = 0F;
      onChanged();
      return this;
    }

    private float yPercent_ ;
    /**
     * <pre>
     * Vertical position [0.0 - 1.0]
     * </pre>
     *
     * <code>float y_percent = 3;</code>
     * @return The yPercent.
     */
    @java.lang.Override
    public float getYPercent() {
      return yPercent_;
    }
    /**
     * <pre>
     * Vertical position [0.0 - 1.0]
     * </pre>
     *
     * <code>float y_percent = 3;</code>
     * @param value The yPercent to set.
     * @return This builder for chaining.
     */
    public Builder setYPercent(float value) {

      yPercent_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vertical position [0.0 - 1.0]
     * </pre>
     *
     * <code>float y_percent = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearYPercent() {
      bitField0_ = (bitField0_ & ~0x00000004);
      yPercent_ = 0F;
      onChanged();
      return this;
    }

    private int scrollDeltaX_ ;
    /**
     * <pre>
     * Scroll offsets (only for ACTION_SCROLL)
     * </pre>
     *
     * <code>int32 scroll_delta_x = 4;</code>
     * @return The scrollDeltaX.
     */
    @java.lang.Override
    public int getScrollDeltaX() {
      return scrollDeltaX_;
    }
    /**
     * <pre>
     * Scroll offsets (only for ACTION_SCROLL)
     * </pre>
     *
     * <code>int32 scroll_delta_x = 4;</code>
     * @param value The scrollDeltaX to set.
     * @return This builder for chaining.
     */
    public Builder setScrollDeltaX(int value) {

      scrollDeltaX_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Scroll offsets (only for ACTION_SCROLL)
     * </pre>
     *
     * <code>int32 scroll_delta_x = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearScrollDeltaX() {
      bitField0_ = (bitField0_ & ~0x00000008);
      scrollDeltaX_ = 0;
      onChanged();
      return this;
    }

    private int scrollDeltaY_ ;
    /**
     * <code>int32 scroll_delta_y = 5;</code>
     * @return The scrollDeltaY.
     */
    @java.lang.Override
    public int getScrollDeltaY() {
      return scrollDeltaY_;
    }
    /**
     * <code>int32 scroll_delta_y = 5;</code>
     * @param value The scrollDeltaY to set.
     * @return This builder for chaining.
     */
    public Builder setScrollDeltaY(int value) {

      scrollDeltaY_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 scroll_delta_y = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearScrollDeltaY() {
      bitField0_ = (bitField0_ & ~0x00000010);
      scrollDeltaY_ = 0;
      onChanged();
      return this;
    }

    private int pointerCount_ ;
    /**
     * <pre>
     * For multi-touch gestures
     * </pre>
     *
     * <code>uint32 pointer_count = 6;</code>
     * @return The pointerCount.
     */
    @java.lang.Override
    public int getPointerCount() {
      return pointerCount_;
    }
    /**
     * <pre>
     * For multi-touch gestures
     * </pre>
     *
     * <code>uint32 pointer_count = 6;</code>
     * @param value The pointerCount to set.
     * @return This builder for chaining.
     */
    public Builder setPointerCount(int value) {

      pointerCount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * For multi-touch gestures
     * </pre>
     *
     * <code>uint32 pointer_count = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPointerCount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      pointerCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tabdisplay.InputEvent)
  }

  // @@protoc_insertion_point(class_scope:tabdisplay.InputEvent)
  private static final com.tabdisplay.client.proto.InputEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tabdisplay.client.proto.InputEvent();
  }

  public static com.tabdisplay.client.proto.InputEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InputEvent>
      PARSER = new com.google.protobuf.AbstractParser<InputEvent>() {
    @java.lang.Override
    public InputEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InputEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InputEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tabdisplay.client.proto.InputEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

