// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

@com.google.protobuf.Generated
public interface InputEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tabdisplay.InputEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.tabdisplay.InputEvent.ActionType action = 1;</code>
   * @return The action.
   */
  com.tabdisplay.client.proto.InputEvent.ActionType getAction();

  /**
   * <pre>
   * Horizontal position [0.0 - 1.0]
   * </pre>
   *
   * <code>float x_percent = 2;</code>
   * @return The xPercent.
   */
  float getXPercent();

  /**
   * <pre>
   * Vertical position [0.0 - 1.0]
   * </pre>
   *
   * <code>float y_percent = 3;</code>
   * @return The yPercent.
   */
  float getYPercent();

  /**
   * <pre>
   * Scroll offsets (only for ACTION_SCROLL)
   * </pre>
   *
   * <code>int32 scroll_delta_x = 4;</code>
   * @return The scrollDeltaX.
   */
  int getScrollDeltaX();

  /**
   * <code>int32 scroll_delta_y = 5;</code>
   * @return The scrollDeltaY.
   */
  int getScrollDeltaY();

  /**
   * <pre>
   * For multi-touch gestures
   * </pre>
   *
   * <code>uint32 pointer_count = 6;</code>
   * @return The pointerCount.
   */
  int getPointerCount();
}
