// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

@com.google.protobuf.Generated
public interface KeepAliveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tabdisplay.KeepAlive)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Monotonic server/client system timestamp
   * </pre>
   *
   * <code>uint64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>uint32 sequence = 2;</code>
   * @return The sequence.
   */
  int getSequence();
}
