// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

/**
 * <pre>
 * Telemetry feedback from Android Client to macOS Server for Adaptive Bitrate
 * </pre>
 *
 * Protobuf type {@code tabdisplay.TelemetryFeedback}
 */
@com.google.protobuf.Generated
public final class TelemetryFeedback extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tabdisplay.TelemetryFeedback)
    TelemetryFeedbackOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "TelemetryFeedback");
  }
  // Use TelemetryFeedback.newBuilder() to construct.
  private TelemetryFeedback(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TelemetryFeedback() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_TelemetryFeedback_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_TelemetryFeedback_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_TelemetryFeedback_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tabdisplay.client.proto.TelemetryFeedback.class, com.tabdisplay.client.proto.TelemetryFeedback.Builder.class);
  }

  public static final int PACKET_LOSS_RATE_FIELD_NUMBER = 1;
  private float packetLossRate_ = 0F;
  /**
   * <pre>
   * Percentage of packets dropped [0.0 - 100.0]
   * </pre>
   *
   * <code>float packet_loss_rate = 1;</code>
   * @return The packetLossRate.
   */
  @java.lang.Override
  public float getPacketLossRate() {
    return packetLossRate_;
  }

  public static final int AVERAGE_JITTER_MS_FIELD_NUMBER = 2;
  private float averageJitterMs_ = 0F;
  /**
   * <pre>
   * Latency jitter in milliseconds
   * </pre>
   *
   * <code>float average_jitter_ms = 2;</code>
   * @return The averageJitterMs.
   */
  @java.lang.Override
  public float getAverageJitterMs() {
    return averageJitterMs_;
  }

  public static final int END_TO_END_LATENCY_MS_FIELD_NUMBER = 3;
  private float endToEndLatencyMs_ = 0F;
  /**
   * <pre>
   * Total elapsed frame latency measured by client
   * </pre>
   *
   * <code>float end_to_end_latency_ms = 3;</code>
   * @return The endToEndLatencyMs.
   */
  @java.lang.Override
  public float getEndToEndLatencyMs() {
    return endToEndLatencyMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(packetLossRate_) != 0) {
      output.writeFloat(1, packetLossRate_);
    }
    if (java.lang.Float.floatToRawIntBits(averageJitterMs_) != 0) {
      output.writeFloat(2, averageJitterMs_);
    }
    if (java.lang.Float.floatToRawIntBits(endToEndLatencyMs_) != 0) {
      output.writeFloat(3, endToEndLatencyMs_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (java.lang.Float.floatToRawIntBits(packetLossRate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, packetLossRate_);
    }
    if (java.lang.Float.floatToRawIntBits(averageJitterMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, averageJitterMs_);
    }
    if (java.lang.Float.floatToRawIntBits(endToEndLatencyMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, endToEndLatencyMs_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tabdisplay.client.proto.TelemetryFeedback)) {
      return super.equals(obj);
    }
    com.tabdisplay.client.proto.TelemetryFeedback other = (com.tabdisplay.client.proto.TelemetryFeedback) obj;

    if (java.lang.Float.floatToIntBits(getPacketLossRate())
        != java.lang.Float.floatToIntBits(
            other.getPacketLossRate())) return false;
    if (java.lang.Float.floatToIntBits(getAverageJitterMs())
        != java.lang.Float.floatToIntBits(
            other.getAverageJitterMs())) return false;
    if (java.lang.Float.floatToIntBits(getEndToEndLatencyMs())
        != java.lang.Float.floatToIntBits(
            other.getEndToEndLatencyMs())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKET_LOSS_RATE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPacketLossRate());
    hash = (37 * hash) + AVERAGE_JITTER_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAverageJitterMs());
    hash = (37 * hash) + END_TO_END_LATENCY_MS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEndToEndLatencyMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tabdisplay.client.proto.TelemetryFeedback parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tabdisplay.client.proto.TelemetryFeedback parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.tabdisplay.client.proto.TelemetryFeedback parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tabdisplay.client.proto.TelemetryFeedback prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Telemetry feedback from Android Client to macOS Server for Adaptive Bitrate
   * </pre>
   *
   * Protobuf type {@code tabdisplay.TelemetryFeedback}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tabdisplay.TelemetryFeedback)
      com.tabdisplay.client.proto.TelemetryFeedbackOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_TelemetryFeedback_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_TelemetryFeedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tabdisplay.client.proto.TelemetryFeedback.class, com.tabdisplay.client.proto.TelemetryFeedback.Builder.class);
    }

    // Construct using com.tabdisplay.client.proto.TelemetryFeedback.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      packetLossRate_ = 0F;
      averageJitterMs_ = 0F;
      endToEndLatencyMs_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tabdisplay.client.proto.Events.internal_static_tabdisplay_TelemetryFeedback_descriptor;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.TelemetryFeedback getDefaultInstanceForType() {
      return com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance();
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.TelemetryFeedback build() {
      com.tabdisplay.client.proto.TelemetryFeedback result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tabdisplay.client.proto.TelemetryFeedback buildPartial() {
      com.tabdisplay.client.proto.TelemetryFeedback result = new com.tabdisplay.client.proto.TelemetryFeedback(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tabdisplay.client.proto.TelemetryFeedback result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.packetLossRate_ = packetLossRate_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.averageJitterMs_ = averageJitterMs_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endToEndLatencyMs_ = endToEndLatencyMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tabdisplay.client.proto.TelemetryFeedback) {
        return mergeFrom((com.tabdisplay.client.proto.TelemetryFeedback)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tabdisplay.client.proto.TelemetryFeedback other) {
      if (other == com.tabdisplay.client.proto.TelemetryFeedback.getDefaultInstance()) return this;
      if (java.lang.Float.floatToRawIntBits(other.getPacketLossRate()) != 0) {
        setPacketLossRate(other.getPacketLossRate());
      }
      if (java.lang.Float.floatToRawIntBits(other.getAverageJitterMs()) != 0) {
        setAverageJitterMs(other.getAverageJitterMs());
      }
      if (java.lang.Float.floatToRawIntBits(other.getEndToEndLatencyMs()) != 0) {
        setEndToEndLatencyMs(other.getEndToEndLatencyMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              packetLossRate_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 21: {
              averageJitterMs_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              endToEndLatencyMs_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float packetLossRate_ ;
    /**
     * <pre>
     * Percentage of packets dropped [0.0 - 100.0]
     * </pre>
     *
     * <code>float packet_loss_rate = 1;</code>
     * @return The packetLossRate.
     */
    @java.lang.Override
    public float getPacketLossRate() {
      return packetLossRate_;
    }
    /**
     * <pre>
     * Percentage of packets dropped [0.0 - 100.0]
     * </pre>
     *
     * <code>float packet_loss_rate = 1;</code>
     * @param value The packetLossRate to set.
     * @return This builder for chaining.
     */
    public Builder setPacketLossRate(float value) {

      packetLossRate_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Percentage of packets dropped [0.0 - 100.0]
     * </pre>
     *
     * <code>float packet_loss_rate = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketLossRate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      packetLossRate_ = 0F;
      onChanged();
      return this;
    }

    private float averageJitterMs_ ;
    /**
     * <pre>
     * Latency jitter in milliseconds
     * </pre>
     *
     * <code>float average_jitter_ms = 2;</code>
     * @return The averageJitterMs.
     */
    @java.lang.Override
    public float getAverageJitterMs() {
      return averageJitterMs_;
    }
    /**
     * <pre>
     * Latency jitter in milliseconds
     * </pre>
     *
     * <code>float average_jitter_ms = 2;</code>
     * @param value The averageJitterMs to set.
     * @return This builder for chaining.
     */
    public Builder setAverageJitterMs(float value) {

      averageJitterMs_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Latency jitter in milliseconds
     * </pre>
     *
     * <code>float average_jitter_ms = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAverageJitterMs() {
      bitField0_ = (bitField0_ & ~0x00000002);
      averageJitterMs_ = 0F;
      onChanged();
      return this;
    }

    private float endToEndLatencyMs_ ;
    /**
     * <pre>
     * Total elapsed frame latency measured by client
     * </pre>
     *
     * <code>float end_to_end_latency_ms = 3;</code>
     * @return The endToEndLatencyMs.
     */
    @java.lang.Override
    public float getEndToEndLatencyMs() {
      return endToEndLatencyMs_;
    }
    /**
     * <pre>
     * Total elapsed frame latency measured by client
     * </pre>
     *
     * <code>float end_to_end_latency_ms = 3;</code>
     * @param value The endToEndLatencyMs to set.
     * @return This builder for chaining.
     */
    public Builder setEndToEndLatencyMs(float value) {

      endToEndLatencyMs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total elapsed frame latency measured by client
     * </pre>
     *
     * <code>float end_to_end_latency_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndToEndLatencyMs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      endToEndLatencyMs_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:tabdisplay.TelemetryFeedback)
  }

  // @@protoc_insertion_point(class_scope:tabdisplay.TelemetryFeedback)
  private static final com.tabdisplay.client.proto.TelemetryFeedback DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tabdisplay.client.proto.TelemetryFeedback();
  }

  public static com.tabdisplay.client.proto.TelemetryFeedback getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TelemetryFeedback>
      PARSER = new com.google.protobuf.AbstractParser<TelemetryFeedback>() {
    @java.lang.Override
    public TelemetryFeedback parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TelemetryFeedback> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TelemetryFeedback> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tabdisplay.client.proto.TelemetryFeedback getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

