// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

@com.google.protobuf.Generated
public interface TelemetryFeedbackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tabdisplay.TelemetryFeedback)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Percentage of packets dropped [0.0 - 100.0]
   * </pre>
   *
   * <code>float packet_loss_rate = 1;</code>
   * @return The packetLossRate.
   */
  float getPacketLossRate();

  /**
   * <pre>
   * Latency jitter in milliseconds
   * </pre>
   *
   * <code>float average_jitter_ms = 2;</code>
   * @return The averageJitterMs.
   */
  float getAverageJitterMs();

  /**
   * <pre>
   * Total elapsed frame latency measured by client
   * </pre>
   *
   * <code>float end_to_end_latency_ms = 3;</code>
   * @return The endToEndLatencyMs.
   */
  float getEndToEndLatencyMs();
}
