// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shared/proto/events.proto
// Protobuf Java Version: 4.35.1

package com.tabdisplay.client.proto;

/**
 * <pre>
 * Video transport protocol negotiated at handshake time
 * </pre>
 *
 * Protobuf enum {@code tabdisplay.VideoTransport}
 */
@com.google.protobuf.Generated
public enum VideoTransport
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Wi-Fi mode: standard UDP datagrams
   * </pre>
   *
   * <code>UDP = 0;</code>
   */
  UDP(0),
  /**
   * <pre>
   * USB mode: reliable TCP stream tunnelled over adb forward
   * </pre>
   *
   * <code>TCP = 1;</code>
   */
  TCP(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "VideoTransport");
  }
  /**
   * <pre>
   * Wi-Fi mode: standard UDP datagrams
   * </pre>
   *
   * <code>UDP = 0;</code>
   */
  public static final int UDP_VALUE = 0;
  /**
   * <pre>
   * USB mode: reliable TCP stream tunnelled over adb forward
   * </pre>
   *
   * <code>TCP = 1;</code>
   */
  public static final int TCP_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VideoTransport valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static VideoTransport forNumber(int value) {
    switch (value) {
      case 0: return UDP;
      case 1: return TCP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VideoTransport>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VideoTransport> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VideoTransport>() {
          public VideoTransport findValueByNumber(int number) {
            return VideoTransport.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.tabdisplay.client.proto.Events.getDescriptor().getEnumType(0);
  }

  private static final VideoTransport[] VALUES = values();

  public static VideoTransport valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private VideoTransport(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tabdisplay.VideoTransport)
}

